#!/usr/bin/env python
import sys, os

components = ['gtest', '..']
recurse    = lambda ctx : map(lambda proj: ctx.recurse(proj), components)

def check_version_cxx(cfg):
    error = "g++-4.7, clang-3.1 or newer required"

    cfg.check_cxx(
        msg      = "Checking compiler version",
        errmsg   = error,
        type     = "cxx",
        cxxflags = "-std=c++11",
        execute  = False,
        fragment = """
                       #if __cplusplus != 201103L
                         #error %(MSG)s
                       #endif
                   """ % { "MSG" : error })

def options(opt):
    opt.load('g++')
    opt.load('boost')

    recurse(opt)

def configure(cfg):
    cfg.load('g++')
    cfg.load('boost')

    recurse(cfg)

    cfg.check_boost(
            lib='serialization system thread',
            uselib_store='BOOST')

    cfg.env.CXXFLAGS_0TLTEST = [
            '-std=c++11',
            '-g', '-O1',
            '-pedantic',
            '-Wall',
            '-Wextra',
            '-ftemplate-depth=1500',
            #'-D_GLIBCXX_PROFILE',
            #'-D_GLIBCXX_DEBUG',
            ]

    cfg.env.LIB_0TLTEST       = ['pthread']
    cfg.env.INCLUDES_0TLTEST  = ['.']

    check_version_cxx(cfg)

def build(bld):
    recurse(bld)

    bld(
        target          = 'main',
        features        = 'cxx cxxprogram',
        source          = bld.path.get_src().ant_glob('*.cc'),
        use             = ['0TLTEST', 'ZTL', 'BOOST', 'gtest'],
        install_path    = 'bin',
    )
