#!/usr/bin/env python
import sys, os


def check_version_cc(cfg):
    error = "g++-4.7, clang-3.1 or newer required"

    cfg.check_cxx(
        msg      = "Checking compiler version",
        errmsg   = error,
        type     = "cxx",
        cxxflags = cfg.env.CXXFLAGS_0TLTEST,
        execute  = False,
        fragment = """
                       #if __cplusplus != 201103L
                         #error %(MSG)s
                       #endif
                   """ % { "MSG" : error })

def options(opt):
    opt.recurse('gtest')
    opt.load('g++')
    opt.load('boost')

def configure(cfg):
    cfg.recurse('gtest')
    cfg.load('g++')
    cfg.load('boost')

    cfg.check_boost(
            lib='serialization system thread',
            uselib_store='BOOST')

    cfg.env.CXXFLAGS_0TLTEST = [
            '-std=c++0x',
            '-g', '-O1',
            '-pedantic',
            '-Wall',
            '-Wextra',
            '-ftemplate-depth=1500',
            #'-D_GLIBCXX_PROFILE',
            #'-D_GLIBCXX_DEBUG',
            ]

    cfg.env.LIB_0TLTEST       = ['pthread']
    cfg.env.INCLUDES_0TLTEST  = ['..']

    check_version_cc(cfg)

def build(bld):
    bld.recurse('gtest')

    bld(
        target          = 'main',
        features        = 'cxx cxxprogram',
        source          = bld.path.get_src().ant_glob('*.cc'),
        use             = ['0TLTEST', 'BOOST', 'gtest'],
    )
